require:
  - rubocop-rake
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - ./*.gemspec

Naming/FileName:
  Exclude:
    - lib/rubocop-thinkific.rb

RSpec/ExampleLength:
  Max: 10

AllCops:
  NewCops: enable